title: Ananya
description: My Personal Blog
author: Ananya
logo: /static/img/avatar.png
github: https://github.com/ananyaiitbhilai
about: Student

baseurl: "https://ananyaiitbhilai.github.io/ananya-blog"
url: "https://ananyaiitbhilai.github.io/ananya-blog"

allowsearch: true

disqus_shortname: ananya
google_analytics: UA-72862926-1

share:
  twitter_username: \#
  fb_appid: 000000000000


enableTags: true
tagarray: []

paginate: 20
per_page: 20
paginate_path: "/page:num/"
markdown: kramdown
gems: [jekyll-paginate, jekyll-gist]
